// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PoliticalAppAPI.Data;

#nullable disable

namespace PoliticalAppAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251211162857_AddAlignmentScoreToUser")]
    partial class AddAlignmentScoreToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PoliticalAppAPI.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillNumber")
                        .HasColumnType("int")
                        .HasColumnName("bill_number");

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("bill_type");

                    b.Property<int>("Congress")
                        .HasColumnType("int")
                        .HasColumnName("congress");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated_utc");

                    b.Property<DateTime?>("LatestActionDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("latest_action_date");

                    b.Property<string>("LatestActionText")
                        .HasColumnType("longtext")
                        .HasColumnName("latest_action_text");

                    b.Property<string>("PolicyArea")
                        .HasColumnType("longtext")
                        .HasColumnName("policy_area");

                    b.Property<string>("SponsorName")
                        .HasColumnType("longtext")
                        .HasColumnName("sponsor_name");

                    b.Property<string>("SummaryText")
                        .HasColumnType("longtext")
                        .HasColumnName("summary_text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("bills");
                });

            modelBuilder.Entity("PoliticalAppAPI.Models.BillVote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("int")
                        .HasColumnName("bill_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_utc");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("user_id");

                    b.Property<int>("Vote")
                        .HasColumnType("int")
                        .HasColumnName("vote");

                    b.HasKey("Id");

                    b.HasIndex("BillId", "UserId")
                        .IsUnique();

                    b.ToTable("bill_votes");
                });

            modelBuilder.Entity("PoliticalAppAPI.Models.Representative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BioguideId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("bioguide_id");

                    b.Property<string>("Chamber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("chamber");

                    b.Property<int?>("DistrictNumber")
                        .HasColumnType("int")
                        .HasColumnName("district_number");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("LastUpdatedUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_updated_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("party");

                    b.Property<int>("StartYear")
                        .HasColumnType("int")
                        .HasColumnName("start_year");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("state_code");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("state_name");

                    b.HasKey("Id");

                    b.ToTable("representatives");
                });

            modelBuilder.Entity("PoliticalAppAPI.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.Property<int?>("AlignmentScore")
                        .HasColumnType("int")
                        .HasColumnName("alignment_score");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("Region")
                        .HasColumnType("longtext")
                        .HasColumnName("region");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("role");

                    b.Property<string>("State")
                        .HasColumnType("longtext")
                        .HasColumnName("state");

                    b.HasKey("UserId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("PoliticalAppAPI.Models.BillVote", b =>
                {
                    b.HasOne("PoliticalAppAPI.Models.Bill", "Bill")
                        .WithMany("Votes")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("PoliticalAppAPI.Models.Bill", b =>
                {
                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
